export const DICE_OFFERS = [
  {
    id: 'over_10_3d',
    dice: 3,
    condition: 'over',
    target: 10,
    payout: 1.5,
    odds: '~75%',
    dealerLine: 'Roll over 10 with three dice. Easy money.',
  },
  {
    id: 'over_13_3d',
    dice: 3,
    condition: 'over',
    target: 13,
    payout: 2,
    odds: '~50%',
    dealerLine: 'Roll over 13 with three dice. Double your winnings or walk away with nothing.',
  },
  {
    id: 'over_15_3d',
    dice: 3,
    condition: 'over',
    target: 15,
    payout: 3,
    odds: '~28%',
    dealerLine: 'Roll over 15 with three dice. Triple your winnings. High risk.',
  },
  {
    id: 'pair_2d',
    dice: 2,
    condition: 'pair',
    target: null,
    payout: 2,
    odds: '~58%',
    dealerLine: 'Roll a matching pair with two dice. Simple enough.',
  },
  {
    id: 'over_10_2d',
    dice: 2,
    condition: 'over',
    target: 10,
    payout: 3,
    odds: '~17%',
    dealerLine: 'Roll over 10 with two dice. The odds are against you.',
  },
  {
    id: 'triple_3d',
    dice: 3,
    condition: 'triple',
    target: null,
    payout: 8,
    odds: '~3%',
    dealerLine: 'Three of a kind. All the same face. Eight times your winnings. Almost impossible.',
  },
]
